### ISSUE TITLE
License

### ISSUE THREAD

**Issue by mfe7** [arobey1/RobustNN#1]
Hi @arobey1, this repo was super helpful in running robustness analysis via SDP. Would you be willing to add a license to this repo so we can adhere to our school's licensing policies when pointing to this repo as a git submodule in [our repo](https://github.com/mit-acl/nn_robustness_analysis)?

**Comment by arobey1** [comment]
Yeah no problem -- see commit 561edd7.  I'm glad this repo was useful :)
